# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, 0, 1121, 601))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 1051, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(800, 20, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(470, 30, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_2.setGeometry(QtCore.QRect(650, 30, 73, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(410, 30, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(600, 30, 55, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_29.setGeometry(QtCore.QRect(210, 30, 171, 31))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_27.setGeometry(QtCore.QRect(840, 480, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1121, 471))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 1111, 491))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(7)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 30, 261, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(532, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formWidget_2.setGeometry(QtCore.QRect(610, 80, 411, 201))
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_20 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.comboBox_12 = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_21 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.comboBox_13 = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox_13.setObjectName("comboBox_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_13)
        self.label_22 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.comboBox_14 = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox_14.setObjectName("comboBox_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_23 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_24 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(30, 80, 491, 251))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setGeometry(QtCore.QRect(170, 10, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_8.setGeometry(QtCore.QRect(640, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 10, 261, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formWidget = QtWidgets.QWidget(self.tab_6)
        self.formWidget.setGeometry(QtCore.QRect(630, 100, 381, 191))
        self.formWidget.setObjectName("formWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_10 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox_7 = QtWidgets.QComboBox(self.formWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_12 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_8 = QtWidgets.QComboBox(self.formWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_11 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_6 = QtWidgets.QComboBox(self.formWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.label_14 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 50, 261, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(572, 10, 171, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(160, 50, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 90, 491, 251))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab)
        self.pushButton_29.setGeometry(QtCore.QRect(870, 490, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget.addTab(self.tab, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_11)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1121, 541))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 1071, 431))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_28.setGeometry(QtCore.QRect(860, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_22.setGeometry(QtCore.QRect(482, 320, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_25.setGeometry(QtCore.QRect(420, 220, 261, 31))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_24.setGeometry(QtCore.QRect(420, 150, 261, 31))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_35 = QtWidgets.QLabel(self.tab_13)
        self.label_35.setGeometry(QtCore.QRect(270, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_17 = QtWidgets.QLabel(self.tab_13)
        self.label_17.setGeometry(QtCore.QRect(270, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_34 = QtWidgets.QLabel(self.tab_13)
        self.label_34.setGeometry(QtCore.QRect(270, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_9.setGeometry(QtCore.QRect(420, 90, 261, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.label_18 = QtWidgets.QLabel(self.tab_14)
        self.label_18.setGeometry(QtCore.QRect(150, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_23.setGeometry(QtCore.QRect(640, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_10.setGeometry(QtCore.QRect(320, 10, 261, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_24.setGeometry(QtCore.QRect(650, 10, 171, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_25.setGeometry(QtCore.QRect(300, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 170, 261, 31))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_26.setGeometry(QtCore.QRect(370, 110, 261, 31))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_37 = QtWidgets.QLabel(self.tab_14)
        self.label_37.setGeometry(QtCore.QRect(220, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_36 = QtWidgets.QLabel(self.tab_14)
        self.label_36.setGeometry(QtCore.QRect(220, 240, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_28.setGeometry(QtCore.QRect(370, 240, 261, 31))
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_19 = QtWidgets.QLabel(self.tab_14)
        self.label_19.setGeometry(QtCore.QRect(220, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 491, 421))
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(80, 80, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(70, 30, 91, 31))
        self.label_8.setObjectName("label_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(172, 300, 131, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_15.setGeometry(QtCore.QRect(200, 130, 261, 41))
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_17.setGeometry(QtCore.QRect(200, 80, 261, 41))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setGeometry(QtCore.QRect(200, 30, 261, 41))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_14.setGeometry(QtCore.QRect(200, 180, 261, 41))
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(82, 130, 91, 31))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(70, 180, 111, 31))
        self.label_5.setObjectName("label_5")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(170, 240, 261, 31))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 30, 471, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(150, 30, 261, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(32, 80, 91, 31))
        self.label_27.setObjectName("label_27")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(150, 70, 261, 31))
        self.lineEdit_19.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(200, 110, 131, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(569, 199, 491, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_23.setGeometry(QtCore.QRect(160, 110, 261, 31))
        self.lineEdit_23.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(70, 70, 71, 31))
        self.label_29.setObjectName("label_29")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(160, 70, 261, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(200, 200, 131, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(60, 110, 91, 31))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(40, 150, 111, 31))
        self.label_31.setObjectName("label_31")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_22.setGeometry(QtCore.QRect(160, 150, 261, 31))
        self.lineEdit_22.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(160, 30, 261, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(60, 30, 91, 31))
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 30, 1051, 431))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 111, 1051, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_14.setGeometry(QtCore.QRect(792, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(222, 30, 191, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_15.setGeometry(QtCore.QRect(800, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_32 = QtWidgets.QLabel(self.tab_9)
        self.label_32.setGeometry(QtCore.QRect(68, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_6.setGeometry(QtCore.QRect(220, 30, 191, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_3.setGeometry(QtCore.QRect(-2, 111, 1051, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_16.setGeometry(QtCore.QRect(800, 29, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_33 = QtWidgets.QLabel(self.tab_8)
        self.label_33.setGeometry(QtCore.QRect(38, 29, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_13.setGeometry(QtCore.QRect(220, 29, 191, 41))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(-2, 110, 1051, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab_5, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 71, 61))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 420, 71, 61))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/themes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 350, 71, 51))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 190, 71, 71))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/auth.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 110, 71, 61))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(890, -40, 311, 541))
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(110, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_17.setGeometry(QtCore.QRect(70, 170, 93, 71))
        self.pushButton_17.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_18.setGeometry(QtCore.QRect(170, 170, 93, 71))
        self.pushButton_18.setStyleSheet("background-color: rgb(38, 50, 56);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_19.setGeometry(QtCore.QRect(170, 250, 93, 71))
        self.pushButton_19.setStyleSheet("background-color: rgb(50, 65, 75);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_20.setGeometry(QtCore.QRect(70, 250, 93, 71))
        self.pushButton_20.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 240, 21, 31))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 270, 71, 61))
        self.pushButton_26.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon5)
        self.pushButton_26.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_26.setObjectName("pushButton_26")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1191, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "To"))
        self.pushButton_6.setText(_translate("MainWindow", "Add"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Book Title"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Retrieve"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Rent"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.label.setText(_translate("MainWindow", "Type"))
        self.label_2.setText(_translate("MainWindow", "Days"))
        self.lineEdit_29.setPlaceholderText(_translate("MainWindow", "Enter Client Name"))
        self.pushButton_27.setText(_translate("MainWindow", "Export Operations  to CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "    Book Name"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Description"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Code"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Book Category"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Book price"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Book Author"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Book Publisher"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "All Books"))
        self.label_3.setText(_translate("MainWindow", "Book Title"))
        self.pushButton_7.setText(_translate("MainWindow", "Save"))
        self.label_20.setText(_translate("MainWindow", "Book Code"))
        self.label_21.setText(_translate("MainWindow", "Category"))
        self.label_22.setText(_translate("MainWindow", " Author"))
        self.label_23.setText(_translate("MainWindow", "Publisher"))
        self.label_24.setText(_translate("MainWindow", "Book Price"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Add New Book"))
        self.label_9.setText(_translate("MainWindow", "Book Title"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.label_13.setText(_translate("MainWindow", "Book Code"))
        self.label_10.setText(_translate("MainWindow", "Category"))
        self.label_12.setText(_translate("MainWindow", " Author"))
        self.label_11.setText(_translate("MainWindow", "Publisher"))
        self.label_14.setText(_translate("MainWindow", "Book Price"))
        self.pushButton_9.setText(_translate("MainWindow", "Search"))
        self.label_25.setText(_translate("MainWindow", "Book Title"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Edit or Delete A Book"))
        self.pushButton_29.setText(_translate("MainWindow", "Export Books Data to CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Email"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Client ID"))
        self.pushButton_28.setText(_translate("MainWindow", "Export Client Data to CSV"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "All Clients"))
        self.pushButton_22.setText(_translate("MainWindow", "Add New Client"))
        self.label_35.setText(_translate("MainWindow", "Client Email"))
        self.label_17.setText(_translate("MainWindow", "Client Name"))
        self.label_34.setText(_translate("MainWindow", "Client Identity"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Add New Client"))
        self.label_18.setText(_translate("MainWindow", "Client National ID"))
        self.pushButton_23.setText(_translate("MainWindow", "Save"))
        self.pushButton_24.setText(_translate("MainWindow", "Search"))
        self.pushButton_25.setText(_translate("MainWindow", "Delete"))
        self.label_37.setText(_translate("MainWindow", "Client Email"))
        self.label_36.setText(_translate("MainWindow", "Client Identity"))
        self.label_19.setText(_translate("MainWindow", "Client Name"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("MainWindow", "Edit or Delete A Client"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Page"))
        self.groupBox.setTitle(_translate("MainWindow", "Add New Users"))
        self.label_7.setText(_translate("MainWindow", "Email"))
        self.label_8.setText(_translate("MainWindow", "User Name"))
        self.pushButton_11.setText(_translate("MainWindow", "Add User"))
        self.label_6.setText(_translate("MainWindow", "PassWord"))
        self.label_5.setText(_translate("MainWindow", "PassWord Again"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit User Information"))
        self.label_26.setText(_translate("MainWindow", "User Name"))
        self.label_27.setText(_translate("MainWindow", "PassWord"))
        self.pushButton_12.setText(_translate("MainWindow", "Login"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Edit User"))
        self.label_29.setText(_translate("MainWindow", "Email"))
        self.pushButton_13.setText(_translate("MainWindow", "Edit User Data"))
        self.label_30.setText(_translate("MainWindow", "PassWord"))
        self.label_31.setText(_translate("MainWindow", "PassWord Again"))
        self.label_28.setText(_translate("MainWindow", "User Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category"))
        self.pushButton_14.setText(_translate("MainWindow", "Add New Category"))
        self.label_4.setText(_translate("MainWindow", "New Category Name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Add Category"))
        self.pushButton_15.setText(_translate("MainWindow", "Add New Author"))
        self.label_32.setText(_translate("MainWindow", "Add New Author"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Author"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Add Author"))
        self.pushButton_16.setText(_translate("MainWindow", "Add New Publisher"))
        self.label_33.setText(_translate("MainWindow", "New Publisher"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Publisher"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Add Publisher"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.label_15.setText(_translate("MainWindow", "Change Theme"))
        self.pushButton_17.setText(_translate("MainWindow", "Dark Orange"))
        self.pushButton_18.setText(_translate("MainWindow", "Plain Blue"))
        self.pushButton_19.setText(_translate("MainWindow", "Blue White"))
        self.pushButton_20.setText(_translate("MainWindow", "Dark Blue"))
        self.pushButton_21.setText(_translate("MainWindow", ">"))

import icon_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

